import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Cities",
  description: "Generated by create next app",
};

export default function CitiesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    < >

          
          {children}

     
    </>
  );
}
