import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Categories",
  description: "Generated by create next app",
};

export default function CategoriesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
          {children}
    </>
  );
}
