import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Sorbon | City",
  description: "Generated by create next app",
};

export default function CityLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    < >

          
          {children}

     
    </>
  );
}
