import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Sorbon | Privacy",
  description: "Generated by create next app",
};

export default function PrivacyLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    < >
      {children}
    </>
  );
}
