import type { Metadata } from "next";
import "./globals.css";
import { Work_Sans } from "next/font/google";
import NavBar from "@/components/NavBar/NavBar";
import Footer from "@/components/footer/Footer";

const workSans = Work_Sans({
  subsets: ["latin"],
  weight: ['400', '700']
});





export const metadata: Metadata = {
  title: "Sorbon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${workSans.className} bg-[#f0effa] min-h-screen max-w-[90rem] grid grid-rows-[110px auto 110px] grid-cols-1  m-auto`}
      >
        <NavBar />
        <main className="flex max-w-full flex-col items-center sm:items-start">
          
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
