import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar/NavBar";
import Footer from "@/components/footer/Footer";
import { Work_Sans } from "next/font/google";

const workSans = Work_Sans({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800'],
});





export const metadata: Metadata = {
  title: "Sorbon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://cdn.example.com/fonts/MadaniArabic-Medium.css" rel="stylesheet" />
      </head>
      <body
        className={`${workSans.className} bg-[#f0effa] min-h-screen max-w-full grid grid-rows-[60px auto 110px] grid-cols-1  m-auto`}
      >
        <NavBar />
        <main className="flex max-w-full flex-col items-center sm:items-start">

          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
