import type { Metadata } from "next";
import "./globals.css";
import { Work_Sans } from "next/font/google";
import NavBar from "@/components/NavBar/NavBar";
import Footer from "@/components/footer/Footer";

const workSans = Work_Sans({
  subsets: ["latin"],
  weight: ['400', '700']
});





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${workSans.className}  min-h-screen max-w-full m-auto`}
      >
        <main className="flex max-w-full flex-col row-start-2 items-center sm:items-start">
          <NavBar />
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
