export type optionsValues = {
    options: string,
    value: string | number,
}
type comboBoxType = {
    lable: string,
    options: {
        options: string,
        value: number,
    }[]
}
export type comboBoxTypeCountry = {
    name: string;
    flag: string;
    phoneSuffix: string;
  };
export const comboBoxData: comboBoxType[] = [
    {

        lable: "Duration",
        options: [
            {
                options: "5 Days",
                value: 5
            },
            {
                options: "10 Days",
                value: 10
            },
            
        ]

    },
   



    // {
    //     lable: "Course type",
    //     options: [
    //         {
    //             options: "Course type",
    //             value: "Course type"
    //         }
    //     ]
    // },
]

export const countryOptions: optionsValues[] = [
    { options: "Afghanistan", value: "Afghanistan" },
    { options: "Albania", value: "Albania" },
    { options: "Algeria", value: "Algeria" },
    { options: "Andorra", value: "Andorra" },
    { options: "Angola", value: "Angola" },
    { options: "Argentina", value: "Argentina" },
    { options: "Armenia", value: "Armenia" },
    { options: "Australia", value: "Australia" },
    { options: "Austria", value: "Austria" },
    { options: "Azerbaijan", value: "Azerbaijan" },
    { options: "Bahrain", value: "Bahrain" },
    { options: "Bangladesh", value: "Bangladesh" },
    { options: "Belarus", value: "Belarus" },
    { options: "Belgium", value: "Belgium" },
    { options: "Belize", value: "Belize" },
    { options: "Benin", value: "Benin" },
    { options: "Bhutan", value: "Bhutan" },
    { options: "Bolivia", value: "Bolivia" },
    { options: "Bosnia and Herzegovina", value: "Bosnia and Herzegovina" },
    { options: "Botswana", value: "Botswana" },
    { options: "Brazil", value: "Brazil" },
    { options: "Brunei", value: "Brunei" },
    { options: "Bulgaria", value: "Bulgaria" },
    { options: "Burkina Faso", value: "Burkina Faso" },
    { options: "Burundi", value: "Burundi" },
    { options: "Cambodia", value: "Cambodia" },
    { options: "Cameroon", value: "Cameroon" },
    { options: "Canada", value: "Canada" },
    { options: "Cape Verde", value: "Cape Verde" },
    { options: "Central African Republic", value: "Central African Republic" },
    { options: "Chad", value: "Chad" },
    { options: "Chile", value: "Chile" },
    { options: "China", value: "China" },
    { options: "Colombia", value: "Colombia" },
    { options: "Comoros", value: "Comoros" },
    { options: "Costa Rica", value: "Costa Rica" },
    { options: "Croatia", value: "Croatia" },
    { options: "Cuba", value: "Cuba" },
    { options: "Cyprus", value: "Cyprus" },
    { options: "Czech Republic", value: "Czech Republic" },
    { options: "Denmark", value: "Denmark" },
    { options: "Djibouti", value: "Djibouti" },
    { options: "Dominica", value: "Dominica" },
    { options: "Dominican Republic", value: "Dominican Republic" },
    { options: "DR Congo", value: "DR Congo" },
    { options: "Ecuador", value: "Ecuador" },
    { options: "Egypt", value: "Egypt" },
    { options: "El Salvador", value: "El Salvador" },
    { options: "Equatorial Guinea", value: "Equatorial Guinea" },
    { options: "Eritrea", value: "Eritrea" },
    { options: "Estonia", value: "Estonia" },
    { options: "Eswatini", value: "Eswatini" },
    { options: "Ethiopia", value: "Ethiopia" },
    { options: "Fiji", value: "Fiji" },
    { options: "Finland", value: "Finland" },
    { options: "France", value: "France" },
    { options: "Gabon", value: "Gabon" },
    { options: "Gambia", value: "Gambia" },
    { options: "Georgia", value: "Georgia" },
    { options: "Germany", value: "Germany" },
    { options: "Ghana", value: "Ghana" },
    { options: "Greece", value: "Greece" },
    { options: "Grenada", value: "Grenada" },
    { options: "Guatemala", value: "Guatemala" },
    { options: "Guinea", value: "Guinea" },
    { options: "Guinea-Bissau", value: "Guinea-Bissau" },
    { options: "Guyana", value: "Guyana" },
    { options: "Haiti", value: "Haiti" },
    { options: "Honduras", value: "Honduras" },
    { options: "Hungary", value: "Hungary" },
    { options: "Iceland", value: "Iceland" },
    { options: "India", value: "India" },
    { options: "Indonesia", value: "Indonesia" },
    { options: "Iran", value: "Iran" },
    { options: "Iraq", value: "Iraq" },
    { options: "Ireland", value: "Ireland" },
    { options: "Israel", value: "Israel" },
    { options: "Italy", value: "Italy" },
    { options: "Ivory Coast", value: "Ivory Coast" },
    { options: "Jamaica", value: "Jamaica" },
    { options: "Japan", value: "Japan" },
    { options: "Jordan", value: "Jordan" },
    { options: "Kazakhstan", value: "Kazakhstan" },
    { options: "Kenya", value: "Kenya" },
    { options: "Kiribati", value: "Kiribati" },
    { options: "Kuwait", value: "Kuwait" },
    { options: "Kyrgyzstan", value: "Kyrgyzstan" },
    { options: "Laos", value: "Laos" },
    { options: "Latvia", value: "Latvia" },
    { options: "Lebanon", value: "Lebanon" },
    { options: "Lesotho", value: "Lesotho" },
    { options: "Liberia", value: "Liberia" },
    { options: "Libya", value: "Libya" },
    { options: "Liechtenstein", value: "Liechtenstein" },
    { options: "Lithuania", value: "Lithuania" },
    { options: "Luxembourg", value: "Luxembourg" },
    { options: "Madagascar", value: "Madagascar" },
    { options: "Malawi", value: "Malawi" },
    { options: "Malaysia", value: "Malaysia" },
    { options: "Maldives", value: "Maldives" },
    { options: "Mali", value: "Mali" },
    { options: "Malta", value: "Malta" },
    { options: "Marshall Islands", value: "Marshall Islands" },
    { options: "Mauritania", value: "Mauritania" },
    { options: "Mauritius", value: "Mauritius" },
    { options: "Mexico", value: "Mexico" },
    { options: "Micronesia", value: "Micronesia" },
    { options: "Moldova", value: "Moldova" },
    { options: "Monaco", value: "Monaco" },
    { options: "Mongolia", value: "Mongolia" },
    { options: "Montenegro", value: "Montenegro" },
    { options: "Morocco", value: "Morocco" },
    { options: "Mozambique", value: "Mozambique" },
    { options: "Myanmar", value: "Myanmar" },
    { options: "Namibia", value: "Namibia" },
    { options: "Nauru", value: "Nauru" },
    { options: "Nepal", value: "Nepal" },
    { options: "Netherlands", value: "Netherlands" },
    { options: "New Zealand", value: "New Zealand" },
    { options: "Nicaragua", value: "Nicaragua" },
    { options: "Niger", value: "Niger" },
    { options: "Nigeria", value: "Nigeria" },
    { options: "North Korea", value: "North Korea" },
    { options: "North Macedonia", value: "North Macedonia" },
    { options: "Norway", value: "Norway" },
    { options: "Oman", value: "Oman" },
    { options: "Pakistan", value: "Pakistan" },
    { options: "Palau", value: "Palau" },
    { options: "Palestine", value: "Palestine" },
    { options: "Panama", value: "Panama" },
    { options: "Papua New Guinea", value: "Papua New Guinea" },
    { options: "Paraguay", value: "Paraguay" },
    { options: "Peru", value: "Peru" },
    { options: "Philippines", value: "Philippines" },
    { options: "Poland", value: "Poland" },
    { options: "Portugal", value: "Portugal" },
    { options: "Qatar", value: "Qatar" },
    { options: "Republic of the Congo", value: "Republic of the Congo" },
    { options: "Romania", value: "Romania" },
    { options: "Russia", value: "Russia" },
    { options: "Rwanda", value: "Rwanda" },
    { options: "Saint Kitts and Nevis", value: "Saint Kitts and Nevis" },
    { options: "Saint Lucia", value: "Saint Lucia" },
    { options: "Saint Vincent and the Grenadines", value: "Saint Vincent and the Grenadines" },
    { options: "Samoa", value: "Samoa" },
    { options: "San Marino", value: "San Marino" },
    { options: "Sao Tome and Principe", value: "Sao Tome and Principe" },
    { options: "Saudi Arabia", value: "Saudi Arabia" },
    { options: "Senegal", value: "Senegal" },
    { options: "Serbia", value: "Serbia" },
    { options: "Seychelles", value: "Seychelles" },
    { options: "Sierra Leone", value: "Sierra Leone" },
    { options: "Singapore", value: "Singapore" },
    { options: "Slovakia", value: "Slovakia" },
    { options: "Slovenia", value: "Slovenia" },
    { options: "Solomon Islands", value: "Solomon Islands" },
    { options: "Somalia", value: "Somalia" },
    { options: "South Africa", value: "South Africa" },
    { options: "South Korea", value: "South Korea" },
    { options: "South Sudan", value: "South Sudan" },
    { options: "Spain", value: "Spain" },
    { options: "Sri Lanka", value: "Sri Lanka" },
    { options: "Sudan", value: "Sudan" },
    { options: "Suriname", value: "Suriname" },
    { options: "Sweden", value: "Sweden" },
    { options: "Switzerland", value: "Switzerland" },
    { options: "Syria", value: "Syria" },
    { options: "Taiwan", value: "Taiwan" },
    { options: "Tajikistan", value: "Tajikistan" },
    { options: "Tanzania", value: "Tanzania" },
    { options: "Thailand", value: "Thailand" },
    { options: "Timor-Leste", value: "Timor-Leste" },
    { options: "Togo", value: "Togo" },
    { options: "Tonga", value: "Tonga" },
    { options: "Trinidad and Tobago", value: "Trinidad and Tobago" },
    { options: "Tunisia", value: "Tunisia" },
    { options: "Turkey", value: "Turkey" },
    { options: "Turkmenistan", value: "Turkmenistan" },
    { options: "Tuvalu", value: "Tuvalu" },
    { options: "Uganda", value: "Uganda" },
    { options: "Ukraine", value: "Ukraine" },
    { options: "United Arab Emirates", value: "United Arab Emirates" },
    { options: "United Kingdom", value: "United Kingdom" },
    { options: "United States", value: "United States" },
    { options: "Uruguay", value: "Uruguay" },
    { options: "Uzbekistan", value: "Uzbekistan" },
    { options: "Vanuatu", value: "Vanuatu" },
    { options: "Vatican City", value: "Vatican City" },
    { options: "Venezuela", value: "Venezuela" },
    { options: "Vietnam", value: "Vietnam" },
    { options: "Yemen", value: "Yemen" },
    { options: "Zambia", value: "Zambia" },
    { options: "Zimbabwe", value: "Zimbabwe" }
];
